config/routes.rb
RedT::Application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users
  resources :posts

   root to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :url, :title, :user_id, presence: true
  validates :url, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts

  validates :username, :email, :password, :password_confirmation, presence: true
  validates :username, :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      return User.find session[:user_id]
    end
  end

  def require_authentication
    redirect_to login_path unless current_user
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_authentication, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.all.order(updated_at: :asc )
    @show_link = true
  end

  def show
    @post = Post.find params[:id]
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.user_id = current_user.id
    @post.save
    redirect_to @post
  end

  def edit
    @post = Post.find params[:id]
    redirect_to root_path
  end

  def update
    @post = Post.find params[:id]
    @post.user_id = current_user.id
    @post.update post_params
    redirect_to @post
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params[:post].permit(:title, :url, :content, :created_at, :updated_at, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to user_path(current_user)
    end
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_authentication, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
    @posts = @user.posts
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    redirect_to @user
  end

  def edit
    @user = User.find params[:id]
    redirect_to root_path
  end

  def update
    @user = User.find params[:id]
    @user.update user_params
    redirect_to @user
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params[:user].permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedT</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Create Account", new_user_path %> <br>
<%= link_to "HOME", root_path %> <br>
<%= link_to "Submit New Post", new_post_path  %> <br>

<br>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <% if  @post.errors.any? %>
    Please correct the following errors:
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %> <br>

  <%= f.label :url %>
  <%= f.text_field :url %> <br>

  <%= f.label :content %>
  <%= f.text_field :content %> <br>

  <%= f.submit %>

<% end %>

app/views/posts/_post.html.erb
<% if @show_link %>
  <h3><%= link_to post.title, post_path(post) %></h3>
  created by <%= link_to post.user.username, user_path(post.user) %> at <%= post.created_at.strftime("%H: %M, %m/%d/%Y") %>
<% else %>
  <h3><%= post.title %> </h3>
  created by <%= link_to post.user.username, user_path(post.user) %> at <%= post.created_at.strftime("%H: %M, %m/%d/%Y") %> <br>

  <br>
  <a href="<%= post.url %>"><%= post.url %></a> <br>

  <br>
  <%= post.content %> <br>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post: <%= @post.title %></h1>

<%= render 'form' %>

<%= link_to "Back to Post", @post %>

app/views/posts/index.html.erb
<%= render @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render @post %>

<br>
<%= link_to "Delete", @post, confirm: 'Are you sure?', method: 'delete' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    Please correct the following errors:
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :username %>
  <%= f.text_field :username %> <br>

  <%= f.label :email %>
  <%= f.text_field :email %> <br>

  <%= f.label :password %>
  <%= f.password_field :password %> <br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %> <br>


  <br>
  <%= f.submit %>

<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <%= user.username %> <br>
  <%= user.email %> <br>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Profile: <%= @user.username %></h1>
<p><%= @user.email %></p>

<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>